server:
    port: ${SERVER_PORT:8081}

spring:
    application:
        name: task-service
    datasource:
        url: jdbc:postgresql://${POSTGRES_USER_HOST:localhost}:5432/task-db
        username: WAVE
        password: den1234567890/
    jpa:
        show-sql: true 
    properties:
        hibernate:
            format_sql: true

eureka:
    client:
        service-url:
            defaultZone: http://${DISCOVERY_HOST:localhost}:8761/eureka

management:
    endpoint:
        restart:
            enabled: true
        health:
            enabled: true
        info: 
            enabled: true

auth:
    host: ${AUTH_HOST:localhost}:8080